### ISSUE TITLE
How to update tags?

### ISSUE THREAD

**Issue by dechimp** [marketplacer/lightspeed_pos#11]
Really enjoying your fork of the project.  I'm not sure if this belongs in the fork or the original, but when trying to update an item's tags:

`my_item.update "tag" => ["foo_bar", "baz", "qux"] `

result:

`Lightspeed::Error::InternalServerError: Can not convert an array to XML when array has numeric indexed values.`

same error with these:
`my_item.update "Tags" => {"tag"=>["foo_bar", "baz", "qux"]}`
`my_item.update  "Tags"=>{"@attributes"=>{"count"=>"3"}, "tag"=>["foo_bar", "baz", "qux"]}`

**Comment by dustMason** [comment]
I haven't tried, but check the official docs for an idea.

http://cloud-docs.lightspeedapp.com/API/APIHelp.help

  my_itemupdate "Tags" => ["foo_bar", "baz", "qux"]

or

  my_itemupdate "Tags" => [{ "Tag" => {"tagID" => 1}}, {"Tag" => {"name" => "foo"}}]

perhaps

**Comment by dechimp** [comment]
I wasn't able to get those to work, but this seemed to work:

`my_item.update "Tags" => [{tag: "foo_bar"}, {tag: "baz"}, {tag: "qux"}]`

Thank you :)

**Comment by dustMason** [comment]
great, thanks for documenting here!
