### ISSUE TITLE
Limit?

### ISSUE THREAD

**Issue by dechimp** [marketplacer/lightspeed_pos#12]
Has anyone figured out a way to set a query limit? For example, limiting a simple GET request would have you do something like 

/API/Account/[account_id]/Item?limit=50

I dont think these are supported:
`first_50 = account.items.all(params: { limit: 50})`
`first_50 = account.items.all(limit: 50)`

**Comment by dechimp** [comment]
Found one way:
`account.items.page(1, per_page: 50)`

**Comment by radar** [comment]
Hey @dechimp: could you submit a PR to add this to the README please? It might be helpful for other people to know this.

**Comment by dechimp** [comment]
Yeah, I will.  First I want to verify that it works well before adding it to the doc.
