### ISSUE TITLE
Relax activesupport dependency?

### ISSUE THREAD

**Issue by allaire** [marketplacer/lightspeed_pos#6]
Getting `Bundler could not find compatible versions for gem "activesupport":`, could we relax the dependency a bit?

Perhaps something like this `  spec.add_dependency "activesupport", "~> 4.2.0"`

Or maybe there's a reason it's pinned to 4.2.3 ?

Thanks!

**Comment by radar** [comment]
Hey @allaire. There's no reason it's pinned to 4.2.3. If you want to submit a PR for removing that strictness and backing it off to `~> 4.2.0` we'd gladly accept.

**Comment by allaire** [comment]
here: https://github.com/marketplacer/lightspeed_pos/pull/7

**Comment by radar** [comment]
Fixed by #7.
