### ISSUE TITLE
Unsure how to use to_json on collection?

### ISSUE THREAD

**Issue by allaire** [marketplacer/lightspeed_pos#8]
Currently I've only get it to work by doing the following:

```
    employees = account.employees.all
    render json: account.employees.to_json
```

if I don't call `.all` before, it's not working, and I can't chain `.to_json` on all because it returns stack level too deep error

**Comment by allaire** [comment]
@dustMason Maybe you're familiar with this?

**Comment by dustMason** [comment]
I think implementing `all` on Lightspeed::Employees is the right way to go, so that part looks fine. You might have an easier time debugging the `to_json` issue using the console included in this project rather than from within rails. Try `bin/console` from the root of this repo and typing `account.employees.all` from there. You'll need a .env file with your API credentials.

**Comment by allaire** [comment]
@dustMason Thanks for your quick reply. No luck here, I still get stack level too deep when with the code below:

```ruby

  before_action :set_client

  def employees
    account = @client.accounts.first

    puts account.items.all.to_json

    render json: account.employees.all, each_serializer: ::Integrations::LightspeedRetail::EmployeeSerializer, root: :employees
  end

  private

  def set_client
    @client = Lightspeed::Client.new(oauth_token: current_user.lightspeed_retail_token)
  end
```

It breaks at the `puts` line. I found an interesting workaround though with ActiveModelSerializer. I added `alias :read_attribute_for_serialization :send` to ressource.rb and now I can use serializers successfully. I have no idea why now I don't have to use `to_json`, but it works.

**Comment by allaire** [comment]
I also get the argument error from the console though, and it gets fixed with your fix. No idea why I get stack level too deep in rails though!

**Comment by dustMason** [comment]
If you only see the error in the rails code and not in the console that
suggests the issue could be related to some rails magic. I'd try using
byebug or pry to break before that line in your controller and step through
the execution to see where the recursion happens.

**Comment by allaire** [comment]
@dustMason I think rails has some magic around `to_json`. I'm sure @radar know a thing or two about this :)

**Comment by radar** [comment]
`all` should return an array, and then `to_json` should just JSONify that array. I am not up-to-speed on the code within this library (it's mainly touched by @dnl and @anakinakova), and so I don't know if they've overridden `to_json` or not. Either way: I'd consider this a bug.

**Comment by dustMason** [comment]
Note that this only occurs in the context of a rails controller.

**Comment by dnl** [comment]
Hi I've resolved this by passing through the arguments sent to `to_json`. 

It seems that when `to_json` `to_json`'s it's children it passes an argument for how it will to_json, so the to_json in the Lightspeed::Resource objects needed to know about it.

**Comment by allaire** [comment]
I think to_json only use an options argument no? http://apidock.com/rails/ActiveRecord/Serialization/to_json

Anyway, I'm still getting the same stack level too deep error in Rails:

`puts @client.accounts.all.to_json`

![2015-11-26 at 22 49](https://cloud.githubusercontent.com/assets/304461/11433781/4a82d1fa-9490-11e5-9533-2042efa6e7ec.png)

**Comment by dnl** [comment]
The first way you wrote is how I expected this to be used (and I thought I was returning self for `Collection#all` anyway...), if you want a one-liner
```
account.employees.tap(&:all).to_json
```

I want to work though, which is why I attempted to fix it. I suspect we just need to implement `as_json` to correspond to the #to_json I currently have,

Can you please try `alias_method :as_json, :to_h` after the `to_h` in Lightspeed::Collection and Lightspeed::Resource, and see if that fixes your endless loop issues.

If that works, feel free to submit a pull request, otherwise let me know and I'll set up a 4.2.1 rails project and see if I can reproduce it.

Thanks,

Dan.

**Comment by allaire** [comment]
@dnl It worked when I modified both `to_h` like this (adding (*args) and the alias):

```ruby
    def to_h(*args)
      return if all_loaded.empty?
      { resource_name => all_loaded.map(&:to_h) }
    end
    alias_method :as_json, :to_h
```

Should I only use options = nil instead since this looks like the exact argument (http://api.rubyonrails.org/classes/ActiveModel/Serializers/JSON.html) ?

Is this a bit hackish? Should we instead implement some kind of ActiveModel stuff in our resource classes instead?

**Comment by dnl** [comment]
excellent.

I've pushed that to master, let me know if you see this issue again.

Thanks for the help solving it.

**Comment by allaire** [comment]
@dnl Great it works well, and now I don't even have to do `.to_json` when I use `render json`:

`render json: @client.accounts.all, status: 200`

Is it because you renamed the method to `as_json` ?

**Comment by dnl** [comment]
ha, cool.
